# Generated by Django 5.2.6 on 2025-09-27 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=128, unique=True, verbose_name='Зав. № машины')),
                ('engine_serial', models.CharField(max_length=128, verbose_name='Зав. № двигателя')),
                ('trans_serial', models.CharField(max_length=128, verbose_name='Зав. № трансмиссии')),
                ('axle_drive_serial', models.CharField(max_length=128, verbose_name='Зав. № ведущего моста')),
                ('axle_steer_serial', models.CharField(max_length=128, verbose_name='Зав. № управляемого моста')),
                ('supply_contract', models.CharField(blank=True, max_length=255, verbose_name='Договор поставки №, дата')),
                ('factory_ship_date', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('consignee', models.CharField(blank=True, max_length=255, verbose_name='Грузополучатель (конечный потребитель)')),
                ('operation_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес поставки (эксплуатации)')),
                ('options', models.TextField(blank=True, verbose_name='Комплектация (доп. опции)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines_as_client', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
                'ordering': ['-factory_ship_date'],
            },
        ),
        migrations.CreateModel(
            name='NamedDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtype', models.CharField(choices=[('model_tech', 'Модель техники'), ('model_engine', 'Модель двигателя'), ('model_trans', 'Модель трансмиссии'), ('model_axle_drive', 'Модель ведущего моста'), ('model_axle_steer', 'Модель управляемого моста'), ('to_type', 'Вид ТО'), ('failure_node', 'Узел отказа'), ('recovery_method', 'Способ восстановления'), ('service_company', 'Сервисная компания')], max_length=40)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
                'indexes': [models.Index(fields=['dtype', 'name'], name='core_namedd_dtype_38bbd4_idx')],
                'unique_together': {('dtype', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проведения ТО')),
                ('uptime_mh', models.PositiveIntegerField(verbose_name='Наработка, м/час')),
                ('order_no', models.CharField(blank=True, max_length=128, verbose_name='№ заказ-наряда')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Дата заказ-наряда')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='core.machine')),
                ('org', models.ForeignKey(limit_choices_to={'dtype': 'service_company'}, on_delete=django.db.models.deletion.PROTECT, related_name='maintenances_as_org', to='core.nameddict', verbose_name='Организация, проводившая ТО')),
                ('service_company', models.ForeignKey(limit_choices_to={'dtype': 'service_company'}, on_delete=django.db.models.deletion.PROTECT, related_name='maintenances_as_service', to='core.nameddict', verbose_name='Сервисная компания')),
                ('to_type', models.ForeignKey(limit_choices_to={'dtype': 'to_type'}, on_delete=django.db.models.deletion.PROTECT, related_name='maintenances_as_type', to='core.nameddict', verbose_name='Вид ТО')),
            ],
            options={
                'verbose_name': 'ТО',
                'verbose_name_plural': 'ТО',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='model_axle_drive',
            field=models.ForeignKey(limit_choices_to={'dtype': 'model_axle_drive'}, on_delete=django.db.models.deletion.PROTECT, related_name='machines_as_drive_axle', to='core.nameddict', verbose_name='Модель ведущего моста'),
        ),
        migrations.AddField(
            model_name='machine',
            name='model_axle_steer',
            field=models.ForeignKey(limit_choices_to={'dtype': 'model_axle_steer'}, on_delete=django.db.models.deletion.PROTECT, related_name='machines_as_steer_axle', to='core.nameddict', verbose_name='Модель управляемого моста'),
        ),
        migrations.AddField(
            model_name='machine',
            name='model_engine',
            field=models.ForeignKey(limit_choices_to={'dtype': 'model_engine'}, on_delete=django.db.models.deletion.PROTECT, related_name='machines_as_engine', to='core.nameddict', verbose_name='Модель двигателя'),
        ),
        migrations.AddField(
            model_name='machine',
            name='model_tech',
            field=models.ForeignKey(limit_choices_to={'dtype': 'model_tech'}, on_delete=django.db.models.deletion.PROTECT, related_name='machines_as_tech', to='core.nameddict', verbose_name='Модель техники'),
        ),
        migrations.AddField(
            model_name='machine',
            name='model_trans',
            field=models.ForeignKey(limit_choices_to={'dtype': 'model_trans'}, on_delete=django.db.models.deletion.PROTECT, related_name='machines_as_trans', to='core.nameddict', verbose_name='Модель трансмиссии'),
        ),
        migrations.AddField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(limit_choices_to={'dtype': 'service_company'}, on_delete=django.db.models.deletion.PROTECT, related_name='machines_as_service_company', to='core.nameddict', verbose_name='Сервисная компания'),
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField(verbose_name='Дата отказа')),
                ('uptime_mh', models.PositiveIntegerField(verbose_name='Наработка, м/час')),
                ('failure_desc', models.TextField(blank=True, verbose_name='Описание отказа')),
                ('used_parts', models.TextField(blank=True, verbose_name='Используемые запасные части')),
                ('recovery_date', models.DateField(verbose_name='Дата восстановления')),
                ('downtime_hours', models.IntegerField(editable=False, verbose_name='Время простоя техники')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='core.machine')),
                ('failure_node', models.ForeignKey(limit_choices_to={'dtype': 'failure_node'}, on_delete=django.db.models.deletion.PROTECT, related_name='claims_as_failure_node', to='core.nameddict', verbose_name='Узел отказа')),
                ('recovery_method', models.ForeignKey(limit_choices_to={'dtype': 'recovery_method'}, on_delete=django.db.models.deletion.PROTECT, related_name='claims_as_recovery_method', to='core.nameddict', verbose_name='Способ восстановления')),
                ('service_company', models.ForeignKey(limit_choices_to={'dtype': 'service_company'}, on_delete=django.db.models.deletion.PROTECT, related_name='claims_as_service', to='core.nameddict', verbose_name='Сервисная компания')),
            ],
            options={
                'verbose_name': 'Рекламация',
                'verbose_name_plural': 'Рекламации',
                'ordering': ['-failure_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
